-   id: ktlint-wrapper
    name: ktlint wrapper
    entry: ./ktlint-wrapper.sh
    language: script
    types: [kotlin]
-   id: detekt-wrapper
    name: detekt wrapper
    entry: ./detekt-wrapper.sh
    language: script
    types: [kotlin]
